"""phase2 knowledge base feedback evaluation tables

Revision ID: 7d2bae6d14b4
Revises: 10b92f276b11
Create Date: 2026-09-19 06:25:18.210646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2bae6d14b4'
down_revision: Union[str, Sequence[str], None] = '10b92f276b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('use_mock_llm', sa.Boolean(), nullable=False),
    sa.Column('total_cases', sa.Integer(), nullable=False),
    sa.Column('passed_cases', sa.Integer(), nullable=False),
    sa.Column('failed_cases', sa.Integer(), nullable=False),
    sa.Column('category_breakdown', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_by', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_number')
    )
    op.create_index(op.f('ix_evaluation_runs_created_at'), 'evaluation_runs', ['created_at'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('index_status', sa.String(length=20), nullable=False),
    sa.Column('index_error', sa.Text(), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('answer_preview', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_results_run_id'), 'evaluation_results', ['run_id'], unique=False)
    op.create_table('knowledge_document_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version', name='uq_kb_doc_version')
    )
    op.create_index(op.f('ix_knowledge_document_versions_document_id'), 'knowledge_document_versions', ['document_id'], unique=False)
    op.create_table('knowledge_index_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('job_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('documents_indexed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_index_jobs_created_at'), 'knowledge_index_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_index_jobs_document_id'), 'knowledge_index_jobs', ['document_id'], unique=False)
    op.create_table('ai_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'message_id', name='uq_feedback_user_message')
    )
    op.create_index(op.f('ix_ai_feedback_created_at'), 'ai_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_feedback_message_id'), 'ai_feedback', ['message_id'], unique=False)
    op.create_index(op.f('ix_ai_feedback_user_id'), 'ai_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_feedback_user_id'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_message_id'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_created_at'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    op.drop_index(op.f('ix_knowledge_index_jobs_document_id'), table_name='knowledge_index_jobs')
    op.drop_index(op.f('ix_knowledge_index_jobs_created_at'), table_name='knowledge_index_jobs')
    op.drop_table('knowledge_index_jobs')
    op.drop_index(op.f('ix_knowledge_document_versions_document_id'), table_name='knowledge_document_versions')
    op.drop_table('knowledge_document_versions')
    op.drop_index(op.f('ix_evaluation_results_run_id'), table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_evaluation_runs_created_at'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    # ### end Alembic commands ###
