"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowRight, Bot, CheckCircle2, Clock3, MessageSquare, Package, Sparkles, Ticket as TicketIcon, TrendingUp, Zap } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { Badge, Button, Card, SkeletonLine } from "@/components/ui/primitives";
import { useAuth } from "@/hooks/use-auth";
import { api } from "@/lib/api";
import { statusTone, titleCase } from "@/lib/utils";
import type { Order, Ticket } from "@/types/api";

const SUGGESTED = ["Where is my order?", "What's your return policy?", "How long does shipping take?", "Talk to a human"];

export default function DashboardPage() {
  const { user } = useAuth();
  const router = useRouter();
  const [orders, setOrders] = useState<Order[] | null>(null);
  const [tickets, setTickets] = useState<Ticket[] | null>(null);
  const [prompt, setPrompt] = useState("");
  useEffect(() => { api.listOrders().then(setOrders).catch(() => setOrders([])); api.listTickets().then(setTickets).catch(() => setTickets([])); }, []);
  async function startChat(message?: string) { const conv = await api.createConversation(); if (message) sessionStorage.setItem(`draft:${conv.id}`, message); router.push(`/chat?c=${conv.id}`); }
  const activeTickets = tickets?.filter((t) => !["resolved", "closed"].includes(t.status)) || [];
  const firstName = user?.full_name?.split(" ")[0] || "there";

  return <AppShell><div className="mx-auto max-w-[1400px] space-y-7 animate-float-in">
    <section className="relative overflow-hidden rounded-3xl bg-[#111827] p-6 text-white shadow-[0_18px_50px_rgba(16,24,40,.18)] md:p-8">
      <div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-indigo-500/20 blur-3xl" /><div className="absolute bottom-0 right-24 h-32 w-32 rounded-full bg-violet-500/15 blur-2xl" />
      <div className="relative flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-[11px] font-semibold text-indigo-200"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400" /> AI workspace online</div><h1 className="text-2xl font-bold tracking-tight md:text-3xl">Good to see you, {firstName}.</h1><p className="mt-2 max-w-xl text-sm leading-6 text-slate-300">Resolve questions faster with your AI support copilot, order context and intelligent workflows in one workspace.</p></div><Button onClick={() => startChat()} className="bg-white text-slate-900 hover:bg-slate-100"><Sparkles className="h-4 w-4 text-indigo-600" /> Open AI Assistant</Button></div>
      <form onSubmit={(e) => { e.preventDefault(); if (prompt.trim()) startChat(prompt.trim()); }} className="relative mt-7 flex flex-col gap-2 rounded-2xl border border-white/10 bg-white/5 p-2 backdrop-blur md:flex-row"><div className="flex flex-1 items-center gap-3 rounded-xl bg-white px-4"><Bot className="h-5 w-5 text-indigo-500" /><input value={prompt} onChange={(e) => setPrompt(e.target.value)} placeholder="Ask Aster AI about an order, policy or support issue…" className="h-12 flex-1 bg-transparent text-sm text-slate-900 outline-none placeholder:text-slate-400" /></div><Button type="submit" className="h-12 bg-indigo-500 hover:bg-indigo-400">Ask AI <ArrowRight className="h-4 w-4" /></Button></form>
      <div className="relative mt-3 flex flex-wrap gap-2">{SUGGESTED.map(q => <button key={q} onClick={() => startChat(q)} className="rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs text-slate-300 transition hover:bg-white/10 hover:text-white">{q}</button>)}</div>
    </section>

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={MessageSquare} label="AI conversations" value={"" + (tickets?.length ?? 0)} helper="Across your support history" /><Metric icon={TicketIcon} label="Active tickets" value={"" + activeTickets.length} helper="Needs your attention" /><Metric icon={Package} label="Orders" value={"" + (orders?.length ?? 0)} helper="In your account" /><Metric icon={Zap} label="AI assistance" value="24/7" helper="Always available" /></div>

    <div className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><section><SectionHeader title="Recent orders" href="/orders" /><div className="space-y-2">{orders === null && [1,2].map(i => <SkeletonLine key={i} className="h-20 w-full" />)}{orders?.length === 0 && <Card className="p-8"><Empty icon={Package} title="No orders yet" description="Your order activity will appear here." href="/chat" /></Card>}{orders?.slice(0,4).map(o => <Link key={o.id} href={`/orders/${o.id}`}><Card className="group flex items-center justify-between p-4 transition hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-md"><div className="flex min-w-0 items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600"><Package className="h-4 w-4" /></div><div className="min-w-0"><p className="text-sm font-bold text-slate-900">{o.order_number}</p><p className="truncate text-xs text-slate-500">{o.items[0]?.product_name}{o.items.length > 1 ? ` +${o.items.length - 1} more` : ""}</p></div></div><div className="flex items-center gap-3"><Badge tone={statusTone(o.status)}>{titleCase(o.status)}</Badge><ArrowRight className="h-4 w-4 text-slate-300 transition group-hover:translate-x-1 group-hover:text-indigo-500" /></div></Card></Link>)}</div></section>
      <section><SectionHeader title="Support health" href="/tickets" /><Card className="overflow-hidden"><div className="border-b border-slate-100 p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Current status</p><p className="mt-1 text-lg font-bold text-slate-900">Everything looks good</p></div><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-600"><CheckCircle2 className="h-6 w-6" /></div></div></div><div className="space-y-4 p-5"><HealthRow icon={Clock3} label="Open tickets" value={activeTickets.length.toString()} /><HealthRow icon={TrendingUp} label="AI first response" value="Fast" /><HealthRow icon={Zap} label="Automation" value="Enabled" /></div><Link href="/tickets" className="flex items-center justify-between border-t border-slate-100 px-5 py-4 text-xs font-semibold text-indigo-600 hover:bg-indigo-50/50">View support center <ArrowRight className="h-4 w-4" /></Link></Card></section></div>

    <section><SectionHeader title="Active support" href="/tickets" /><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{tickets === null && [1,2,3].map(i => <SkeletonLine key={i} className="h-24 w-full" />)}{tickets !== null && activeTickets.length === 0 && <div className="md:col-span-2 xl:col-span-3"><Card className="p-8"><Empty icon={CheckCircle2} title="No open tickets" description="You're all caught up. Start a new AI conversation whenever you need help." href="/chat" /></Card></div>}{activeTickets.slice(0,3).map(t => <Link key={t.id} href={`/tickets/${t.id}`}><Card className="group h-full p-4 transition hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-md"><div className="flex items-center justify-between"><span className="text-[11px] font-bold text-slate-400">#{t.ticket_number}</span><Badge tone={statusTone(t.status)}>{titleCase(t.status)}</Badge></div><p className="mt-3 line-clamp-2 text-sm font-semibold text-slate-900">{t.subject}</p><div className="mt-4 flex items-center gap-1 text-xs font-semibold text-slate-400 group-hover:text-indigo-600">Open ticket <ArrowRight className="h-3 w-3" /></div></Card></Link>)}</div></section>
  </div></AppShell>;
}
function Metric({ icon: Icon, label, value, helper }: any) { return <Card className="p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold tracking-tight text-slate-900">{value}</p><p className="mt-1 text-[11px] text-slate-400">{helper}</p></div><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600"><Icon className="h-5 w-5" /></div></div></Card>; }
function SectionHeader({ title, href }: { title: string; href: string }) { return <div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-bold text-slate-900">{title}</h2><Link href={href} className="flex items-center gap-1 text-xs font-semibold text-slate-500 hover:text-indigo-600">View all <ArrowRight className="h-3 w-3" /></Link></div>; }
function HealthRow({ icon: Icon, label, value }: any) { return <div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-100 text-slate-500"><Icon className="h-4 w-4" /></div><span className="text-sm text-slate-600">{label}</span></div><span className="text-xs font-bold text-slate-900">{value}</span></div>; }
function Empty({ icon: Icon, title, description, href }: any) { return <div className="flex flex-col items-center text-center"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-100 text-slate-400"><Icon className="h-5 w-5" /></div><p className="mt-3 text-sm font-bold text-slate-900">{title}</p><p className="mt-1 max-w-xs text-xs leading-5 text-slate-500">{description}</p><Link href={href} className="mt-4 text-xs font-bold text-indigo-600">Get started →</Link></div>; }
